### ISSUE TITLE
Friction parameters are missing

### ISSUE THREAD

**Issue by johnblommers** [rheactron/double_pendulum#1]
This is an enhancement request to add frictional parameters in the equations. The user can control them at startup time in order to provide more realism to the simulation.

I understand this was not your initial intent but this addition would be  useful to folks like me who are tying to understand chaotic systems.

**Comment by rheactive** [comment]
Added friction (a single parameter is enough, I just included dissipative force, proportional to speed). You can even change it during the simulation.
